export default {
  loading: "Đang tải dữ liệu..",
  noData: "Chưa có dữ liệu",
  tryAgain: "Thử lại",
  networkError:
    "Đã có lỗi xảy ra, vui lòng kiểm tra kết nối trên thiết bị của bạn",
  titleError: "Lỗi",
  titleMessage: "Thông báo",
  labelOK: "Đồng ý",
  labelCancel: "Hủy",
  noMoreData: "Dữ liệu đang được cập nhật.",
  signIn: "Đăng nhập",
  signOut: "Đăng xuất",
  nextMonth: "Tháng sau",
  prevMonth: "Tháng trước",
  signOutTitlte: "Đăng xuất",
  signOutConfirmMessage: "Bạn muốn thoát tài khoản này?",
  signOutPostive: "Thoát",
  signOutNavigate: "Hủy",
  next: "TIẾP",
  username: "Tài khoản",
  password: "Mật khẩu",
  ok: "OK",
  dongY: "Đồng ý",
  huy: "Hủy",
  thongBao: "Thông báo",
  login: "Đăng nhập",
  required: "chưa nhập",
  tooShort: "quá ngắn",
  inValid: "không hợp lệ",
  xacNhan: "Xác nhận",
  capNhat: "Cập nhật"
};
