"use strict";

import screen from "../../core/config/screens";

export const screenNames = {
  ...screen,
  Main: "Main",
  TabScreens: "TabScreens",
  DrawerScreens: "DrawerScreens",
  StackScreens: "StackScreens",
  Tab1: "Tab1",
  Tab2: "Tab2",
  Detail: "Detail",
  KhaoSat: "KhaoSat",
  ChiTietKhaoSat: "ChiTietKhaoSat",
  GopY: "GopY",
  ChiTietGopY: "ChiTietGopY",
  GuiGopY: "GuiGopY",
  SoTay: "SoTay",
  ChiTietSoTay: "ChiTietSoTay",
  Hotline: "Hotline",
  Login: "Login",
  CapNhatSoDienThoai: "CapNhatSoDienThoai",
  ThongBao: "ThongBao",
  ThongTinTaiKhoan: "ThongTinTaiKhoan",
  ChiTietThongBao: "ChiTietThongBao",
  ThongTinUngDung: "ThongTinUngDung",
  CropImage: "CropImage",
  CongDong: "CongDong",
  DangKySDT: "DangKyTaiKhoan",
  ThemCanHo: "ThemCanHo",
  DanhSachTinh: "DanhSachTinh",
  DanhSachHuyen: "DanhSachHuyen",
  DanhSachChungCu: "DanhSachChungCu",
  DanhSachToaNha: "DanhSachToaNha",
  DanhSachTang: "DanhSachTang",
  TaoBaiViet: "TaoBaiViet",
  DanhSachCongDong: "DanhSachCongDong",
  SuaBaiViet: "SuaBaiViet",
  ChiTietBaiViet: "ChiTietBaiViet",
  DanhSachSanPhamTrongDanhMuc: "DanhSachSanPhamTrongDanhMuc",
  ChiTietSanPham: "ChiTietSanPham",
  ChiTietDonHang: "ChiTietDonHang",
  TaoGianHang: "TaoGianHang",
  TaoSanPham: "TaoSanPham",
  ChiTietGianHang: "ChiTietGianHang",
  DanhSachDonBan: "DanhSachDonBan",
  DatHang: "DatHang",
  DanhSachDonMua: "DanhSachDonMua",
  CodeScanner: "CodeScanner",
  DanhSachGoiDichVu: "DanhSachGoiDichVu",
  LichSuMuaGoiDichVu: "LichSuMuaGoiDichVu",
  DanhSachNotification: "DanhSachNotification",
  TimKiemSanPham: "TimKiemSanPham",
  DanhSachThanhVien: "DanhSachThanhVien"
};

export const screenLabels = {
  Tab1: "Tab1",
  Tab2: "Tab2",
  TabKhaoSat: "Khảo sát",
  TabGopY: "Góp ý",
  TabSoTay: "Sổ tay",
  TabCongDong: "Cộng đồng",
  TabThongBao: "Thông báo"
};
