// const HOST = "http://113.190.240.90:2004"; //local public
// const HOST = "http://192.168.100.43:1004"; //local private
const HOST = "http://cudandientu.com";
const version = "/api/resident/v1/";
export const API = {
  HOST,
  DANG_NHAP: "Account/login",
  DANG_NHAP_MXH: "Account/login_social",
  DANG_XUAT: "account/logout",
  LAY_THONG_TIN_TAI_KHOAN: "account/info",
  DOI_MAT_KHAU: "account/change_password",
  DS_KHAO_SAT: "Survey/list",
  DS_GOP_Y: "mail/list",
  CHI_TIET_GOP_Y: "mail/detail",
  CHI_TIET_KHAO_SAT: "Survey/detail",
  GUI_GOP_Y: "mail/send",
  XOA_GOP_Y: "mail/delete",
  DANH_MUC_GOP_Y: "mail/mail_category",
  DS_NHOM_QUAN_TRI: "apartment/group",
  GUI_LUA_CHON_KHAO_SAT: "Survey/submit",
  SO_TAY_DAN_CU_DANH_SACH: "Faq/list",
  SO_TAY_DAN_CU_CHI_TIET: "Faq/detail",
  SO_TAY_DAN_CU_DANH_MUC: "Faq/category",
  HOTLINE: "account/hotline",
  DS_THONG_BAO: "Notification/list",
  CHI_TIET_THONG_BAO: "Notification/detail",
  XOA_THONG_BAO: "Notification/remove",
  THONG_TIN_UNG_DUNG: "account/policy",
  XOA_KHAO_SAT: "Survey/remove",
  QUEN_MK_GUI_EMAIL: "Account/forgot_password",
  QUEN_MK_XAC_THUC: "Account/forgot_password_verify_code",
  QUEN_MK_DOI_MAT_KHAU: "Account/forgot_password_change_password",
  DANG_KY_SDT: "Account/register",
  KIEM_TRA_MAT_KHAU: "Account/check_password",
  DANH_SACH_TINH: "Apartment/list_province",
  DANH_SACH_TINH_CO_CHUNG_CU: "Apartment/list_province_has_apartment",
  DANH_SACH_HUYEN: "Apartment/list_district",
  DANH_SACH_HUYEN_CO_CHUNG_CU: "Apartment/list_district_has_apartment",
  DANH_SACH_CHUNG_CU: "Apartment/list",
  DANH_SACH_TOA_NHA: "Apartment/list_building",
  THEM_CAN_HO: "Account/resident_home",
  LAY_THONG_TIN_XE_CO: "note_fee/info_vehicle",
  XOA_CAN_HO: "Account/resident_home_remove",
  DANH_SACH_BAI_VIET: "post/list",
  LIKE_BAI_VIET: "post/like",
  DISLIKE_BAI_VIET: "post/dislike",
  XOA_BAI_VIET: "post/delete",
  TAO_BAI_VIET: "post/create",
  CHI_TIET_BAI_VIET: "post/detail",
  DANH_SACH_COMMENT: "post/comment",
  TAO_COMMENT: "post/comment",
  XOA_COMMENT: "post/comment_delete",
  THEM_MAT_KHAU: "account/update_password_social",
  DANH_SACH_TAT_CA_SAN_PHAM: "product/list_by_category",
  CHI_TIET_SAN_PHAM: "product/detail",
  DS_DANH_MUC: "product/category",
  TAO_SAN_PHAM: "product/create",
  TIM_KIEM_SAN_PHAM: "product/search",
  XOA_SAN_PHAM: "product/delete",
  DS_SAN_PHAM_THEO_DANH_GIA: "product/list_by_star",
  DS_SAN_PHAM_GAN_TOI: "product/list_by_distance",
  DANH_SACH_SAN_PHAM_THEO_DANH_MUC: "product/list_by_category",
  DANH_SACH_GIAN_HANG: "store/list",
  TAO_MOI_GIAN_HANG: "store/create",
  CHI_TIET_GIAN_HANG: "store/detail",
  XOA_GIAN_HANG: "store/delete",
  KHOA_GIAN_HANG: "store/valid",
  KHOA_SAN_PHAM: "product/valid",
  DANH_SACH_SAN_PHAM_TRONG_GIAN_HANG: "store/list_product",
  DANH_SACH_DON_BAN: "order/list_sale",
  CHI_TIET_DON_BAN: "order/detail_sale",
  XU_LY_DON_HANG: "order/update_status",
  THANH_TOAN_XEM_LIEN_HE: "order/on_pay",
  DANH_SACH_DON_MUA: "order/list_buy",
  CHI_TIET_DON_MUA: "order/detail_buy",
  DAT_HANG_SAN_PHAM: "order/create",
  DANH_GIA_SAN_PHAM: "order/rate",
  DANH_GIA_NGUOI_MUA: "order/rate_user",
  COUNT_DON_BAN_PENDING: "order/total_pending",
  HOP_DONG_DIEN_TU: "/hop-dong-dien-tu.html",
  DS_SAN_PHAM_THEO_DE_XUAT: "product/list_by_recommend",
  DANH_SACH_GOI_DICH_VU: "service_package/list",
  LICH_SU_MUA_GOI_DICH_VU: "service_package/history",
  DANH_SACH_NOTIFICATION: "notify/list",
  RESET_NOTIFICATION: "notify/reset_total",
  READ_NOTIFICATION: "notify/view",
  DANH_SACH_THANH_VIEN: "apartment/member_community"
};

export function getApiUrl(api) {
  if (api) {
    return HOST + version + api;
  }
  console.warn("apiURL is empty");
}

export const actionTypes = {
  USER_INFO: "UserInfo",
  LOGIN: "Login",
  LOGOUT: "Logout"
};
