import strings from "../../core/config/strings";

export default {
  ...strings,
  trangChu: "Trang chủ",
  timKiemSanPham: "Tìm kiếm sản phẩm",
  dichVu: "Chợ sinh viên",
  cuDan: "Sinh viên",
  taiKhoan: "Tài khoản",
  logout: "Đăng xuất",
  khaoSat: "Khảo sát",
  daHetHan: "Đã hết hạn",
  xoa: "Xóa",
  chiTietKhaoSat: "Chi tiết khảo sát",
  luotChon: "lượt chọn",
  kDateFormat: "DD/MM/YYYY",
  vuiLongTraLoiCauHoi: "Vui lòng trả lời câu hỏi",
  banMuonGuiCauTraLoi: "Bạn muốn gửi câu trả lời?",
  banMuonGuiDangKy: "Bạn muốn gửi đăng ký?",
  soTayDanCu: "Sổ tay sinh viên",
  chonTinh: "Chọn tỉnh",
  chonHuyen: "Chọn huyện",
  chonXa: "Chọn chung cư",
  chiTiet: "Chi tiết",
  tatCaDanhMuc: "Tất cả danh mục",
  chonDanhMuc: "Chọn danh mục",
  hotline: "Hotline",
  thongBao: "Thông báo",
  khoaGianHang: "Bạn có muốn khóa gian hàng này không?",
  moKhoaGianHang: "Bạn có muốn mở khóa gian hàng này không?",
  moKhoaSanPham: "Bạn có muốn mở khóa sản phẩm này không?",
  KhoaSanPham: "Bạn có muốn khóa sản phẩm này không?",
  chiTietThongBao: "Chi tiết thông báo",
  chonCanHo: "Chọn lớp",
  tatCaCanHo: "Tất cả lớp",
  tu: "Từ",
  toi: "Tới",
  ngay: "Ngày",
  danhGia: "Đánh giá",
  vuiLongCho: "Vui lòng chờ",
  xoaThongBaoDaChon: "Xóa thông báo đã chọn?",
  chonThongBaoDeXoa: "Chọn thông báo để xóa",
  ngayHetHan: "Ngày hết hạn: ",
  banCoMuonXoaThongBao: "Bạn muốn xóa thông báo này?",
  caNhan: "Cá nhân",
  canHo: "Lớp",
  canhBao: "Luu ý",
  thongTinUngDung: "Thông tin ứng dụng",
  tatCaChungCu: "Tất cả trường",
  banHayChonChungCu: "Vui lòng chọn trường trước",
  gianHangDaKhoa: "Gian hàng đã khóa",
  xoaKhaoSatDaChon: "Xoá khảo sát đã chọn?",
  chonKhaoSatDeXoa: "Chọn khảo sát để xóa",
  chamDeCapNhat: "Chạm vào đây để thêm thông tin trường lớp của bạn",
  vuiLongNhapDayDuThongTin:
    "Vui lòng thêm thông tin trường lớp của bạn để sử dụng các tiện ích dành cho sinh viên.",
  capNhat: "Cập nhật",
  congDong: "Diễn đàn",
  soTay: "Sổ tay",
  soChiTieu: "Sổ chi tiêu",
  danhSachTinh: "Danh sách tỉnh",
  danhSachHuyen: "Danh sách huyện",
  danhSachChungCu: "Danh sách trường",
  danhSachToaNha: "Danh sách khoa",
  danhSachTang: "Danh sách chuyên ngành",
  gopY: "Góp ý",
  nhapThongTinDeSuDungTinhNangNay:
    "Vui lòng thêm thông tin trường lớp của bạn để sử dụng tiện ích này",
  quenMatKhau: "Quên mật khẩu",
  nhapEmailXacThuc: "Nhập email xác thực",
  nhapMaXacThuc: "Nhập mã xác thực",
  doiMatKhau: "Đổi mật khẩu",
  nhapLaiMatKhauMoi: "Nhập lại mật khẩu mới",
  matKhauMoi: "Mật khẩu mới",
  matKhauHienTai: "Mật khẩu hiện tại",
  doiMatKhauThanhCong: "Đổi mật khẩu thành công",
  dangKy: "Đăng ký",
  hoVaTen: "Họ và tên",
  chuaNhap: "Chưa nhập",
  quaNgan: "Quá ngắn",
  quaDai: "Quá dài",
  chuaNhapSDT: "Chưa nhập số điện thoại",
  chuaNhapHoTen: "Chưa nhập họ tên",
  dangNhap: "Đăng nhập",
  dangKyThanhCong: "Đăng ký tài khoản thành công",
  dangKyTaiKhoan: "Đăng ký tài khoản",
  khongCoQuetVanTay:
    "Thiết bị của bạn không có chức năng quét vân tay, bạn không thể đăng ký vân tay cho thiết bị này",
  chuaLuuVanTay:
    "Thiết bị của bạn chưa có vân tay nào được lưu. Bạn vui lòng vào cài đặt thiết bị để thêm vân tay",
  nhapMatKhau: "Nhập mật khẩu",
  matKhau: "Mật khẩu",
  saiMatKhau: "Sai mật khẩu, vui lòng nhập lại",
  dangKyVanTayThanhCong: "Đăng ký vân tay thành công",
  emailKhongHopLe: "Email không hợp lệ",
  chuaNhapEmail: "Chưa nhập Email",
  chuaNhapMaXacThuc: "Chưa nhập mã xác thực",
  chuaNhapMatKhauMoi: "Chưa nhập mật khẩu mới",
  chuaNhapLaiMatKhauMoi: "Chưa nhập lại mật khẩu mới",
  matKhauKhongKhop: "Mật khẩu không khớp",
  myhomePay: "Myhome Pay",
  dangKyVanTay: "Đăng ký vân tay",
  dangKyGianHang: "Đăng ký gian hàng",
  donDatHang: "Đơn đặt hàng",
  lichSuMuaHang: "Lịch sử mua hàng",
  dieuKhoanVaChinhSach: "Điều khoản và chính sách",
  chonBanGhiDeXoa: "Chọn bản ghi để xóa",
  chonChungCu: "Chọn trường",
  chonTang: "Chọn chuyên ngành",
  nhapSoPhong: "Nhập tên lớp",
  luuThongTin: "Lưu thông tin",
  vuiLongChonChungCu: "Vui lòng chọn trường",
  vuiLongChonTinh: "Vui lòng chọn tỉnh",
  vuiLongChonHuyen: "Vui lòng chọn huyện",
  vuiLongChonToaNha: "Vui lòng chọn khoa",
  vuiLongChonTang: "Vui lòng chọn chuyên ngành",
  vuiLongNhapSoPhong: "Vui lòng nhập tên lớp",
  daCoLoiXayRa: "Đã có lỗi xảy ra, xin vui lòng thử lại",
  soPhongPlaceholder: "Nhập tên lớp (vd: D9CNPM, D11TMĐT)",
  banCoChacMuonXoaGopYNay: "Bạn có chắc muốn xóa góp ý này?",
  banMuonGuiGopYNay: "Bạn muốn gửi góp ý này?",
  noiDung: "Nội dung",
  tieuDe: "Tiêu đề",
  guiGopY: "Gửi góp ý",
  gopYVeViec: "Góp ý về việc:",
  vuiLongChonNoiNhanGopY: "Vui lòng chọn nơi nhận góp ý trước khi gửi",
  vuiLongNhapTieuDe: "Vui lòng nhập tiêu đề trước khi gửi",
  vuiLongNhapNoiDung: "Vui lòng nhập nội dung trước khi gửi",
  chungCu: "Trường",
  guiToi: "Gửi tới",
  banQuanLy: "Ban quản lý",
  banQuanTri: "Ban quản trị",
  chuDauTu: "Chủ đầu tư",
  veViec: "Về việc",
  danhSachCongDongDaThamGia: "Diễn đàn đã tham gia",
  dongYVoi: 'Bằng việc chọn "Đăng ký" bạn đã đồng ý với',
  cuaUngDung: "của ứng dụng",
  daCoTaiKhoan: "Đã có tài khoản",
  vuiLongNhapNoiDungTruocKhiDang: "Vui lòng nhập nội dung trước khi đăng bài",
  banMuonDangBaiVietNay: "Bạn muốn đăng bài viết này?",
  dong: "Đóng",
  taoBaiViet: "Tạo bài viết",
  chonCongDong: "Chọn diễn đàn:",
  chuaNhapMatKhau: "Chưa nhập mật khẩu",
  sdtPhai10Hoac11So: "Số điện thoại phải là 10 hoặc 11 số",
  matKhauPhaiTu6Den32KyTu: "Mật khẩu phải từ 6 đến 32 ký tự",
  banChiDuocChonToiDa5Anh: "Bạn chỉ được chọn tối đa 5 ảnh",
  capNhatThanhCong: "Cập nhật thành công",
  themMoiThanhCong: "Thêm mới thành công",
  themMoiCanHoThanhCong: "Thêm mới lớp thành công",
  suaBaiViet: "Sửa bài viết",
  congDongDaChon: "Diễn đàn:",
  nhapNoiDung: "Vui lòng nhập nội dung",
  capNhatThayDoi: "Bạn có muốn cập nhật những thay đổi không?",
  matKhauKhongChinhXac: "Mật khẩu không chính xác",
  hoTenPhaiTu3Den30KyTu: "Họ tên phải từ 3 đến 30 ký tự",
  tenSanPhamKhongDuocVuotQua100KyTu:
    "Tên sản phẩm không được vượt quá 100 ký tự",
  hoTenKhongDuocChuaKyTuDacBiet:
    "Họ tên không được chứa số hoặc ký tự đặc biệt",
  chonToaNha: "Chọn khoa",
  maXacThucDaGuiDenEmail: "Mã xác thực đã được gửi đến email của bạn",
  thongTinTaiKhoan: "Thông tin tài khoản",
  dangKyVanTayKhongKhaDung:
    "Đăng ký vân tay không khả dụng đối với tài khoản này",
  chiTietBaiViet: "Chi tiết bài viết",
  comment: "Bình luận",
  xemCacBinhLuanTruoc: "Xem các bình luận trước",
  khongBinhLuanQuaDai: "Nội dung bình luận không vượt quá 500 ký tự",
  banChacChanMuonXoaBinhLuanNay: "Bạn chắc chắn muốn xóa bình luận này?",
  maXacThuc: "Mã xác thực",
  tinh: "Tỉnh",
  huyen: "Huyện",
  toaNha: "Khoa",
  tang: "Chuyên ngành",
  soPhong: "Tên lớp",
  anhChungThuc: "Xác minh bằng thẻ sinh viên của bạn",
  khongCoBinhLuan: "Không có bình luận nào cho bài viết này",
  soPhongInvalid:
    'Tên lớp bao gồm chữ cái, chữ số, dấu gạch ngang "-" và dấu chấm "." ',
  soPhongMaxLength: "Tên lớp không được quá 11 ký tự",
  sua: "Sửa",
  xoaBaiViet: "Bạn có chắc chắn muốn xóa bài viết này không?",
  thuLai: "Thử lại",
  boQua: "Bỏ qua",
  baiVietDaDuocXoa: "Đã xoá bài viết.",
  khongCoChungCu:
    "Khu vực bạn chọn hiện chưa có trường nào, vui lòng thử lại sau.",
  guiCauTraLoiThanhCong: "Gửi câu trả lời thành công",
  daXoaBinhLuan: "Đã xóa bình luận",
  khongCoToaNha:
    "Trường bạn chọn hiện chưa có khoa nào được cấu hình, vui lòng thử lại sau.",
  nhapEmailDangKy: "Nhập email đăng ký",
  xoaThongBaoThanhCong: "Xóa thông báo thành công",
  dangBaiVietThanhCong: "Đăng bài viết thành công",
  tatCa: "Tất cả",
  soPhongInvalidStart:
    'Tên lớp không được bắt đầu và kết thúc bằng dấu gạch ngang "-" hoặc dấu chấm "."',
  soPhongInvalidMultiDot:
    'Tên lớp không được có 2 dấu gạch ngang "-" hoặc 2 dấu chấm "." liền nhau',
  soPhongInvalidDotHyphen:
    'Dấu gạch ngang "-" và dấu chấm "." không được liền nhau',
  khongCoHotline: "Không có hotline",
  khongCoThongBao: "Không có thông báo",
  khongCoKhaoSat: "Không có khảo sát",
  khongCoGopY: "Không có góp ý",
  khongCoSoTay: "Không có sổ tay",
  quayLai: "Quay lại",
  xemThem: "Xem thêm",
  soPhongPhaiKhacKhong: "Tên lớp phải khác 0",
  guiGopYThanhCong: "Gửi góp ý thành công",
  xoaGopYDaChon: "Xóa góp ý đã chọn?",
  xoaGopYThanhCong: "Xóa góp ý thành công",
  xoaCacKhaoSatDaChon: "Xóa các khảo sát đã chọn?",
  xoaCacGopYDaChon: "Xóa các góp ý đã chọn?",
  xoaCacThongBaoDaChon: "Xóa các thông báo đã chọn?",
  xoaDuLieuThanhCong: "Xóa dữ liệu thành công",
  canHoChuaDuocCauHinh:
    "Lớp bạn chọn hiện chưa được cấu hình ban quản lý hoặc ban quản trị. Vui lòng thử lại sau.",
  dongY: "Đồng ý",
  khongPhaiSdt: "Không phải số điện thoại",
  sdtKhongDung: "Số điện thoại không đúng",
  banChuaDangKyVanTayTrongCaiDat: "Bạn chưa đăng ký vân tay trong cài đặt",
  dangNhapTruocRoiDangKyVanTay:
    "Vui lòng đăng nhập bằng mật khẩu trước. Sau đó kích hoạt đăng nhập bằng vân tay trong phần cài đặt để sử dụng",
  xinMoiQuetVanTayDeDangNhap: "Xin mời quét vân tay để đăng nhập",
  soDienThoai: "Số điện thoại",
  xacThucVanTay: "Xác thực vân tay",
  khongCoBaiViet: "Không có bài viết",
  timKiem: "Tìm kiếm",
  sdtKhongHopLe: "Số điện thoại không hợp lệ",
  nhapSdt: "Nhập số điện thoại",
  hoanThanh: "Hoàn thành",
  hoanTatDangNhap: "Hoàn tất đăng nhập",
  chuaCoTen: "(Chưa có tên)",
  chuaCoEmail: "(Chưa có email)",
  bienSoXe: "Biển số xe",
  nhapMatKhauDeDangKyVanTay: "Vui lòng nhập lại mật khẩu để đăng ký vân tay",
  canHoChuaDuocPheDuyetHome:
    "Lớp của bạn chưa được phê duyệt. Vui lòng chờ phê duyệt để sử dụng các tiện ích dành cho sinh viên.",
  canHoChuaDuocPheDuyet: "Vui lòng chờ phê duyệt để sử dụng tiện ích này.",
  themCanHo: "Thêm lớp",
  tatCaCongDong: "Tất cả diễn đàn",
  banCoChacMuonXoaBaiVietNay: "Bạn có chắc chắn muốn xóa bài viết này không?",
  taiKhoanCuaBanChuaCoMatKhau:
    "Tài khoản của bạn chưa có mật khẩu, vui lòng cập nhật mật khẩu để sử dụng tính năng này",
  capNhatMatKhau: "Cập nhật mật khẩu",
  themMatKhauThanhCong:
    "Thêm mật khẩu thành công, vui lòng đăng ký lại vân tay",
  vuiLongChonCongDongTruocKhiDang: "Vui lòng chọn diễn đàn bạn muốn đăng bài.",
  thongBaoNhapEmail:
    "Vui lòng cập nhật email để có thể nhận thông báo về tài khoản của bạn từ chúng tôi.",
  chuaNhapMatKhauHienTai: "Chưa nhập mật khẩu hiện tại",
  matKhauHienTaiPhaiTu6Den32KyTu: "Mật khẩu hiện tại phải từ 6 đến 32 ký tự",
  matKhauMoiPhaiTu6Den32KyTu: "Mật khẩu mới phải từ 6 đến 32 ký tự",
  matKhauMoiPhaiKhacMatKhauHienTai: "Mật khẩu mới phải khác mật khẩu hiện tại",
  mayAnh: "Máy ảnh",
  thuVien: "Thư viện",
  chonAnh: "Chọn ảnh",
  chupAnh: "Chụp ảnh",
  chuaCoSdt: "(Chưa có số điện thoại)",
  dangTrong: " đăng trong ",
  chiTietSanPham: "Chi tiết sản phẩm",
  cacSanPhamCungGianHang: "Các sản phẩm khác của gian hàng",
  gianHang: "Gian hàng",
  datHang: "Đặt hàng",
  sanPhamNoiBat: "Nổi bật",
  xemTatCa: "Xem tất cả",
  sanPhamGanToi: "Gần tôi",
  giaTangDan: "Giá tăng dần",
  giaGiamDan: "Giá giảm dần",
  sapXepTheo: "Sắp xếp theo",
  gia: "Giá: ",
  thoiGianDat: "Thời gian đặt",
  lienHe: "Liên hệ",
  soDienThoaiLienHe: "Số điện thoại liên hệ",
  choXacNhan: "Chờ xác nhận",
  daXacNhan: "Đã xác nhận",
  daGiaoHang: "Đã giao hàng",
  daHuy: "Đã hủy",
  khongCoDonHang: "Không có đơn hàng",
  chiTietDonHang: "Chi tiết đơn hàng",
  loaiSanPham: "Loại sản phẩm: ",
  huyGiaoHang: "Hủy giao hàng",
  xacNhanDonHang: "Xác nhận đơn hàng",
  soLuong: "Số lượng",
  xemLienHe: "Xem liên hệ",
  banVuiLongTraPhiDichVuDeXemDuocLienHeNay:
    "Bạn vui lòng trả phí dịch vụ để xem được liên hệ này",
  chon: "Chọn",
  taoGianHang: "Tạo gian hàng",
  suaGianHang: "Sửa gian hàng",
  xacNhanYeuCauHienThiThongTinNguoiMua:
    "Xác nhận yêu cầu hiển thị thông tin người mua",
  chiTietGianHang: "Chi tiết gian hàng",
  daDatHang: "Đã đặt hàng",
  hoanThanhGiaoHang: "Hoàn thành giao hàng",
  banXacNhanDonHangNay: "Bạn xác nhận đơn hàng này?",
  banDaHoanThanhGiaoHang: "Bạn đã hoàn thành giao hàng?",
  banChacChanMuonHuyDonHangNay: "Bạn chắc chắn muốn hủy đơn hàng này?",
  xong: "Xong",
  goiDien: "Gọi điện",
  huyDonHang: "Hủy đơn hàng",
  moTaSanPham: "Mô tả sản phẩm",
  xacNhanDatHang: "Xác nhận đặt hàng",
  khongTaiDuocAnh: "Không thể hiển thị hình ảnh này.",
  daNhanHang: "Đã nhận hàng",
  vuiLongNhapSoDienThoai: "Vui lòng nhập số điện thoại",
  banMuonDatHangSanPhamNay: "Bạn muốn đặt hàng sản phẩm này?",
  datHangThanhCong: "Đặt hàng thành công",
  banBoi: "Được bán bởi",
  xemGianHang: "Xem gian hàng",
  duocDanhGiaCao: "Được đánh giá cao",
  danhGiaSanPham: "Đánh giá sản phẩm",
  camOnBanDaDanhGia:
    "Cảm ơn bạn đã đánh giá về chất lượng sản phẩm của chúng tôi!",
  nguoiBanHangSeLienHeVoiBan:
    "Người bán hàng sẽ liên hệ với bạn qua số điện thoại này để xác nhận đơn hàng.",
  tongTien: "Tổng tiền: ",
  khongCoSanPham: "Không có sản phẩm nào",
  thongTinSanPham: "Thông tin sản phẩm",
  thongTinDonHang: "Thông tin đơn hàng",
  maDonHang: "Mã đơn hàng",
  thongTinNguoiMua: "Người mua",
  trangThaiDonHang: "Trạng thái đơn hàng",
  tuChoiDonHang: "Từ chối đơn hàng",
  sao: "sao",
  moiBanDanhGiaSanPham: "Mời bạn đánh giá sản phẩm",
  tuChoiDonHangThanhCong: "Từ chối đơn hàng thành công",
  banChacChanMuonTuChoiDonHangNay: "Bạn chắc chắn muốn từ chối đơn hàng này?",
  banChacChanMuonHuyGiaoHangDonHangNay:
    "Bạn chắc chắn muốn hủy giao hàng đơn hàng này?",
  lichSu: "Lịch sử",
  banChacChanMuonXoaGianHangNayKhong:
    "Bạn có chắc chắn muốn xóa gian hàng này không?",
  xoaGianHangThanhCong: "Xóa gian hàng thành công",
  ngayThamGia: "Đã tham gia ngày ",
  banChuaChonAnhGianHang: "Bạn chưa chọn ảnh đại diện gian hàng",
  banChuaChonAnhBiaGianHang: "Bạn chưa chọn ảnh bìa gian hàng",
  banChuaNhapTenGianHang: "Bạn chưa nhập tên gian hàng",
  banChuaNhapDiaChiGianHang: "Bạn chưa nhập địa chỉ gian hàng",
  banChuaChonToaDoGianHang: "Bạn chưa chọn tọa độ gian hàng",
  banChuaNhapLienHeGianHang: "Bạn chưa nhập liên hệ gian hàng",
  banChuaNhapMoTaGianHang: "Bạn chưa nhập giới thiệu gian hàng",
  gianHangCuaToi: "Gian hàng của tôi",
  moiNhat: "Mới nhất",
  tinhTrangDonHang: "Tình trạng đơn hàng",
  tenGianHang: "Tên gian hàng",
  luu: "Lưu",
  themHinhAnh: "Ảnh đại diện",
  anhSanPham: "Ảnh sản phẩm",
  banChuaNhapTuKhoaTimKiem: "Bạn chưa nhập từ khóa tìm kiếm",
  themAnhBia: "Ảnh bìa",
  diaChiGianHang: "Địa chỉ gian hàng",
  viTriGianHang: "Vị trí gian hàng",
  moTa: "Mô tả",
  gioiThieu: "Giới thiệu",
  gioiThieuGianHang: "Giới thiệu gian hàng",
  sanPham: "Sản phẩm",
  dangSanPhamMoi: "Đăng sản phẩm mới",
  tenGianHangKhongDuocVuotQua50KyTu:
    "Tên gian hàng không được vượt quá 50 ký tự",
  diaChiKhongDuocVuotQua100KyTu: "Địa chỉ không được vượt quá 100 ký tự",
  suaGianHangThanhCong: "Sửa gian hàng thành công",
  danhMuc: "Danh mục",
  xoaCanHoThanhCong: "Xóa lớp thành công",
  chuaNhapHoVaTen: "Chưa nhập họ và tên",
  hoVaTenQuaNgan: "Họ và tên quá ngắn",
  hoVaTenQuaDai: "Họ và tên quá dài",
  emailQuaNgan: "Email quá ngắn",
  emailQuaDai: "Email quá dài",
  taoSanPham: "Đăng sản phẩm mới",
  suaSanPham: "Sửa sản phẩm",
  banMuonXoaSanPhamNay: "Bạn chắc chắn muốn xóa sản phẩm này không?",
  capNhatThongTinThanhCong: "Cập nhật thông tin thành công",
  hopDongDienTu: "Hợp đồng điện tử",
  khongDongY: "Không đồng ý",
  toiDongY: "Tôi đồng ý",
  banChuaChonAnhSanPham: "Bạn chưa chọn ảnh sản phẩm",
  banChuaNhapTenSanPham: "Bạn chưa nhập tên sản phẩm",
  banChuaNhapGiaSanPham: "Bạn chưa nhập giá sản phẩm",
  giaSanPhamNhoHon100: "Giá sản phẩm phải nhỏ hơn 100 triệu",
  banChuaNhapMoTaSanPham: "Bạn chưa nhập mô tả sản phẩm",
  xoaSanPhamThanhCong: "Xóa sản phẩm thành công",
  dangSanPhamMoiThanhCong: "Đăng sản phẩm mới thành công",
  chuaDuocPhepTruyCapViTri:
    "Bạn chưa cho phép ứng dụng sử dụng vị trí, vui lòng cấp quyền sử dụng vị trí cho ứng dụng để xem những sản phẩm/dịch vụ gần bạn.",
  chuaDuocPhepTruyCapViTri1:
    "Bạn chưa cho phép ứng dụng sử dụng vị trí, vui lòng cấp quyền sử dụng vị trí cho ứng dụng để sử dụng chức năng này.",
  chuaBatViTri:
    "Bạn chưa bật vị trí. Vui lòng bật vị trí của thiết bị và thử lại.",
  suaSanPhamThanhCong: "Sửa sản phẩm thành công",
  tenSanPham: "Tên sản phẩm",
  giaSanPham: "Giá sản phẩm",
  dangGiaoHang: "Đang giao hàng",
  choGiaoHang: "Chờ giao hàng",
  banDaNhanDuocHang: "Bạn đã nhận được hàng?",
  soLuongSanPham: "Số lượng sản phẩm",
  themLienHe: "Thêm liên hệ",
  xoaLienHe: "Xóa liên hệ",
  cungGianHang: "Cùng gian hàng",
  donHang: "đơn hàng",
  cungNguoiBan: "Cùng người bán",
  cungLoai: "Cùng loại",
  danhGiaNguoiMua: "Đánh giá người mua",
  danhSachSanPham: "Danh sách sản phẩm",
  huyDonHangThanhCong: "Hủy đơn hàng thành công",
  deXuat: "Đề xuất",
  vuiLongNhapSoLuongSanPham:
    "Vui lòng nhập số lượng sản phẩm trong khoảng từ 1 đến 99",
  vuiLongPhaiNhapSo: "Vui lòng phải nhập số",
  donBan: "Đơn bán",
  daDanhGiaSanPham: "Đã đánh giá sản phẩm",
  danhGiaCuaNguoiMua: "Đánh giá của người mua",
  chuaDanhGia: " (chưa đánh giá)",
  daDanhGia: "Đã đánh giá",
  nguoiMuaDaDanhGia: "Người mua đã đánh giá",
  hienCo: "Hiện có",
  chiPhi: "Chi phí",
  maSanPham: "Mã sản phẩm",
  tuyChon: " (tùy chọn)",
  maSanPhamKhongDuocVuotQua255KyTu: "Mã sản phẩm không được vượt quá 255 ký tự",
  muaGoiDichVu: "Mua gói dịch vụ",
  khaDung: "Khả dụng",
  dangSanPham: "Đăng sản phẩm",
  banMuonChonGoiDichVuNay: "Bạn muốn chọn gói dịch vụ này?",
  xu: "xu",
  banChuaCapQuyenSuDungMayAnh: "Bạn chưa cập quyền sử dụng máy ảnh",
  banChuaCapQuyenSuDungThuVien: "Bạn chưa cập quyền sử dụng thư viện",
  lichSuMuaGoiDichVu: "Lịch sử mua gói dịch vụ",
  xacNhanMatKhau: "Xác nhận mật khẩu",
  emailBiTrung: "Email của bạn đã được sử dụng với tài khoản:",
  emailDaDuocSuDung: "Email đã được sử dụng",
  banCoMuonThayDoiEmail: "Bạn có muốn thay đổi email?",
  sdtBiTrung: "Số điện thoại của bạn đã được sử dụng với tài khoản:",
  sdtDaDuocSuDung: "Số điện thoại đã được sử dụng",
  banCoMuonDongBoTaiKhoan: "Bạn có muốn đồng bộ tài khoản này?",
  dongBo: "Đồng bộ",
  banCoMuonGhiDeThongTinTaiKhoan:
    "Bạn có muốn ghi đè thông tin tài khoản không?",
  khongGhiDe: "Không ghi đè",
  thayDoiEmail: "Thay đổi email",
  giaSanPhamKhongHopLe: "Giá sản phẩm không hợp lệ",
  dangBan: "Đăng bán",
  thanhVien: "Thành viên",
  khongCoThanhVien: "Không có thành viên",
  chiTietGopY: "Chi tiết góp ý",
  phanHoi: "Phản hồi",
  moBan: "Không bán",
  quanTriVien: "Quản trị viên",
  matKhauChinhXac: "Mật khẩu chính xác",
  choXuLy: "Chờ xử lý",
  dangXuLy: "Đang xử lý",
  daXuLy: "Đã xử lý",
  dieuKhoanTaoGianHang: "Điều khoản tạo gian hàng",
  daKhoa: "Đã khóa",
  xoaCanHo: "Xóa lớp",
  chucNang: "Chức năng",
  giaSanPhamPhaiLonHon0: "Giá sản phẩm phải lớn hơn 0",
  banDanhGia: "Bạn đánh giá ",
  huyGiaoHangThanhCong: "Hủy giao hàng thành công",
  giaSanPhamPhaiNhoHon1Ty: "Giá sản phẩm phải nhỏ hơn 1 tỷ",
  moKhoa: "Mở khóa",
  khoa: "Khóa",
  chuaCoDanhGia: "Chưa có đánh giá",
  loi: "Lỗi",
  donMua: "Đơn mua",
  banMuonDangGi: "Bạn muốn đăng gì?",
  chuaDuyet: "Chưa duyệt",
  daDuyet: "Đã duyệt",
  khongDuyet: "Không duyệt",
  lopChuaCapNhat: "(Lớp chưa cập nhật)",
  chuyenNganhChuaCapNhat: "(Chuyên ngành chưa cập nhật)",
  khoaChuaCapNhat: "(Khoa chưa cập nhật)"
};
